### ISSUE TITLE
Rings does not emit any sound

### ISSUE THREAD

**Issue by ilambert** [VCVRack/AudibleInstruments#88] opened 2019-11-07 21:31 UTC
On both of my computers (both running Ubuntu 19.10), for some reason, I cannot use Rings.

All that comes out is a signal of +5v

Attached is a screenshot of the behavior. No twisting of knobs or changing of modes seems to affect this one way or another.

![Screenshot from 2019-11-07 15-29-21](https://user-images.githubusercontent.com/1820726/68429393-9a4fa880-0173-11ea-9fa9-f48fa78b4c80.png)

**Comment by flydoggy** [comment] 2019-11-08 16:58
I was working on a patch today and couldn't get anything out of Resonator, but Southpole Annuli worked fine. I also pulled up an old patch that used to work fine, and now, nothing. The VU meter shows something going to the mixer, but it is inaudible. It's not Mindmeld, it's happening with the MscHack mixers, too.

**Comment by ilambert** [comment] 2019-11-08 19:11
I experience the same behavior with Annuli as well. It was the first thing I thought to do when I noticed this happening with Resonator.

**Comment by briansorahan** [comment] 2019-12-12 19:02
I'm experiencing the same behavior with Resonator on Ubuntu Studio 18.04 and Rack 1.1.6

**Comment by AndrewBelt** [comment] 2020-03-18 18:31
Closing as duplicate of https://github.com/VCVRack/AudibleInstruments/issues/81

**Closed as completed by AndrewBelt** 2020-03-18 18:31 UTC
