### ISSUE TITLE
Low resolution module layouts

### ISSUE THREAD

**Issue by ccerhan** [VCVRack/AudibleInstruments#23] opened 2017-11-05 23:44 UTC
Hello,

As you can see, the modules below are in different resolution. I only tested in macOS. I have mac book pro with retina display and I guess that causes the problem. 

Do you plan to upload _svg_ or high resolution _png_ files for the modules? or is there any possible solution for this issue?

<img width="398" alt="vcrack_low_res" src="https://user-images.githubusercontent.com/2284880/32420319-b6d28ed8-c290-11e7-80b9-acc6c1984558.png">

**Comment by manresa** [comment] 2018-02-24 18:14
I would love to help with this! I have all the Adobe Illustrator files from the [MI repository](https://github.com/pichenettes/eurorack) and can convert to high-res PNG or SVG—I just need to know preferred format, sizes, etc. and where to upload them (I’m new to GitHub & open-source development).

**Comment by evmaki** [comment] 2018-03-07 14:39
@AndrewBelt will this be in the next update? I'm about halfway through converting the faceplates from PNG to SVG but figure I might as well hold off if you're already including it.

**Comment by AndrewBelt** [comment] 2018-03-07 14:45
No, the SVG renderer is not yet capable of rendering the flourishes on the Mutable panels. PNG to SVG is not the way to go. I'll convert from AI to SVG myself, under certain technical constraints when I have time.

**Comment by evmaki** [comment] 2018-03-07 14:49
@AndrewBelt works fine on my end. The flourishes aren't rendering correctly using the original AI files because they're built with compound paths. I converted them to regular shapes (with a bit of handiwork in illustrator) and they look just fine.

**Comment by AndrewBelt** [comment] 2018-03-07 15:05
If you're converting from AI to SVG instead of PNG to SVG, and the titles are there ("Modal Synthesizer", etc), I'll take a look.

**Comment by AndrewBelt** [comment] 2018-03-07 15:39
Oh, I'll need one more thing. Create a layer called "widgets" in Inkscape (assuming you're using that), and place rectangles around each knob, slider, button, port, LED, and LED display, such that the sizes of the rectangles match the sizes in the respective [Component Library](https://github.com/VCVRack/Rack/tree/master/res/ComponentLibrary) widgets. When I get around to it, this is what I'll do, so if you want to replace my work you'll need to do this as well.

**Comment by evmaki** [comment] 2018-03-07 15:53
No problem, I can do that. Is there any specific naming convention needed for the rectangles in the "widgets" layer?

**Comment by AndrewBelt** [comment] 2018-03-07 16:32
No, I don't bother, too much effort.

**Comment by AndrewBelt** [comment] 2018-03-13 08:36
Merged #48

**Closed by AndrewBelt** 2018-03-13 08:36 UTC

**Comment by AndrewBelt** [comment] 2018-03-13 10:21
...or not. I don't see a `widgets` layer in the SVG.
Can you document your procedure so I can reproduce?

**Comment by evmaki** [comment] 2018-03-13 12:11
It's certainly there...though maybe Illustrator didn't export it as a "layer" in the way your script might use. It's in a top-level `<g>` tag with `id="widgets"`

**Comment by AndrewBelt** [comment] 2018-03-13 21:16
Ah, I'll check that.
